-- WhatsNaija AI Database Schema
-- PostgreSQL / Supabase
-- Run this script in your Supabase SQL Editor

-- ============================================================================
-- TABLES
-- ============================================================================

-- Businesses table: Each business owner account
CREATE TABLE IF NOT EXISTS businesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    whatsapp_number TEXT UNIQUE NOT NULL,        -- e.g. "+2348012345678"
    phone_number_id TEXT NOT NULL,               -- Meta's Phone Number ID
    waba_id TEXT NOT NULL,                       -- WhatsApp Business Account ID
    paystack_secret TEXT,                        -- Encrypted Paystack secret key
    business_type TEXT,                          -- "fashion", "food", "beauty", etc.
    tone_preference TEXT DEFAULT 'casual',       -- "formal" | "casual" | "pidgin"
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Knowledge base: Products, FAQs, policies for each business
CREATE TABLE IF NOT EXISTS knowledge_base (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    type TEXT NOT NULL,                          -- "product" | "faq" | "policy" | "greeting"
    question TEXT,                               -- For FAQs
    answer TEXT NOT NULL,
    product_name TEXT,                           -- For products
    price NUMERIC(10, 2),                        -- For products (in Naira)
    description TEXT,                            -- For products
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Conversations: Each WhatsApp conversation thread
CREATE TABLE IF NOT EXISTS conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    customer_phone TEXT NOT NULL,
    customer_name TEXT,
    status TEXT DEFAULT 'bot',                   -- "bot" | "human" | "closed"
    started_at TIMESTAMPTZ DEFAULT now(),
    last_message_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(business_id, customer_phone)          -- One active conversation per customer per business
);

-- Messages: Individual messages in conversations
CREATE TABLE IF NOT EXISTS messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE,
    role TEXT NOT NULL,                          -- "customer" | "bot" | "owner"
    content TEXT NOT NULL,
    wa_message_id TEXT UNIQUE,                   -- WhatsApp message ID (for deduplication)
    wa_status TEXT,                              -- "sent" | "delivered" | "read" | "failed"
    sent_at TIMESTAMPTZ DEFAULT now()
);

-- Leads: Qualified customer records captured during conversations
CREATE TABLE IF NOT EXISTS leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL,
    customer_name TEXT,
    customer_phone TEXT NOT NULL,
    product_interest TEXT,
    budget_range TEXT,
    timeline TEXT,
    status TEXT DEFAULT 'new',                   -- "new" | "contacted" | "converted" | "lost"
    notes TEXT,
    captured_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Payment links: Paystack payment links generated by bot
CREATE TABLE IF NOT EXISTS payment_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL,
    paystack_ref TEXT UNIQUE NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    description TEXT,
    customer_phone TEXT,
    status TEXT DEFAULT 'sent',                  -- "sent" | "clicked" | "paid" | "failed"
    payment_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    paid_at TIMESTAMPTZ
);

-- Bookings: Appointment bookings made through bot
CREATE TABLE IF NOT EXISTS bookings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL,
    customer_name TEXT,
    customer_phone TEXT NOT NULL,
    service TEXT,
    scheduled_at TIMESTAMPTZ NOT NULL,
    duration_minutes INTEGER DEFAULT 60,
    status TEXT DEFAULT 'pending',               -- "pending" | "confirmed" | "cancelled" | "completed"
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Business hours: Available time slots for bookings
CREATE TABLE IF NOT EXISTS business_hours (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    day_of_week INTEGER NOT NULL,               -- 0=Sunday, 1=Monday, ..., 6=Saturday
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Conversation state: Extracted facts and context for ongoing conversations
CREATE TABLE IF NOT EXISTS conversation_state (
    conversation_id UUID PRIMARY KEY REFERENCES conversations(id) ON DELETE CASCADE,
    customer_name TEXT,
    product_interest TEXT,
    budget_range TEXT,
    timeline TEXT,
    last_bot_question TEXT,
    extracted_facts JSONB,                       -- Flexible key-value storage
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_businesses_owner ON businesses(owner_id);
CREATE INDEX IF NOT EXISTS idx_businesses_phone_number_id ON businesses(phone_number_id);
CREATE INDEX IF NOT EXISTS idx_businesses_whatsapp_number ON businesses(whatsapp_number);

CREATE INDEX IF NOT EXISTS idx_knowledge_base_business ON knowledge_base(business_id, type, is_active);

CREATE INDEX IF NOT EXISTS idx_conversations_business ON conversations(business_id, status, last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_customer ON conversations(business_id, customer_phone);

CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_wa_id ON messages(wa_message_id);

CREATE INDEX IF NOT EXISTS idx_leads_business ON leads(business_id, status, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_phone ON leads(customer_phone);

CREATE INDEX IF NOT EXISTS idx_payment_links_business ON payment_links(business_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_links_ref ON payment_links(paystack_ref);

CREATE INDEX IF NOT EXISTS idx_bookings_business ON bookings(business_id, status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_bookings_scheduled ON bookings(scheduled_at);

CREATE INDEX IF NOT EXISTS idx_business_hours_business ON business_hours(business_id, day_of_week, is_active);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_hours ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_state ENABLE ROW LEVEL SECURITY;

-- Businesses: Users can only access their own business
CREATE POLICY "Users can view own business"
    ON businesses FOR SELECT
    USING (auth.uid() = owner_id);

CREATE POLICY "Users can update own business"
    ON businesses FOR UPDATE
    USING (auth.uid() = owner_id);

CREATE POLICY "Users can insert own business"
    ON businesses FOR INSERT
    WITH CHECK (auth.uid() = owner_id);

-- Knowledge base: Users can only access their business's knowledge
CREATE POLICY "Users can view own knowledge base"
    ON knowledge_base FOR SELECT
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Users can insert own knowledge base"
    ON knowledge_base FOR INSERT
    WITH CHECK (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Users can update own knowledge base"
    ON knowledge_base FOR UPDATE
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Users can delete own knowledge base"
    ON knowledge_base FOR DELETE
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

-- Conversations: Users can only see their business's conversations
CREATE POLICY "Users can view own conversations"
    ON conversations FOR SELECT
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Users can update own conversations"
    ON conversations FOR UPDATE
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

-- Messages: Users can only see messages in their conversations
CREATE POLICY "Users can view own messages"
    ON messages FOR SELECT
    USING (conversation_id IN (
        SELECT id FROM conversations
        WHERE business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid())
    ));

CREATE POLICY "Users can insert own messages"
    ON messages FOR INSERT
    WITH CHECK (conversation_id IN (
        SELECT id FROM conversations
        WHERE business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid())
    ));

-- Leads: Users can only see their business's leads
CREATE POLICY "Users can view own leads"
    ON leads FOR SELECT
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Users can update own leads"
    ON leads FOR UPDATE
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

-- Payment links: Users can only see their business's payment links
CREATE POLICY "Users can view own payment links"
    ON payment_links FOR SELECT
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

-- Bookings: Users can only see their business's bookings
CREATE POLICY "Users can view own bookings"
    ON bookings FOR SELECT
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Users can update own bookings"
    ON bookings FOR UPDATE
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

-- Business hours: Users can only manage their business's hours
CREATE POLICY "Users can view own business hours"
    ON business_hours FOR SELECT
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Users can insert own business hours"
    ON business_hours FOR INSERT
    WITH CHECK (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Users can update own business hours"
    ON business_hours FOR UPDATE
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Users can delete own business hours"
    ON business_hours FOR DELETE
    USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

-- Conversation state: Users can only see their business's conversation state
CREATE POLICY "Users can view own conversation state"
    ON conversation_state FOR SELECT
    USING (conversation_id IN (
        SELECT id FROM conversations
        WHERE business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid())
    ));

-- ============================================================================
-- FUNCTIONS & TRIGGERS
-- ============================================================================

-- Update updated_at timestamp automatically
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to relevant tables
CREATE TRIGGER update_businesses_updated_at BEFORE UPDATE ON businesses
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_knowledge_base_updated_at BEFORE UPDATE ON knowledge_base
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_leads_updated_at BEFORE UPDATE ON leads
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_bookings_updated_at BEFORE UPDATE ON bookings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_conversation_state_updated_at BEFORE UPDATE ON conversation_state
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Update conversation last_message_at when new message is added
CREATE OR REPLACE FUNCTION update_conversation_last_message()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE conversations
    SET last_message_at = NEW.sent_at
    WHERE id = NEW.conversation_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_conversation_timestamp AFTER INSERT ON messages
    FOR EACH ROW EXECUTE FUNCTION update_conversation_last_message();

-- ============================================================================
-- COMPLETED
-- ============================================================================

-- Verify installation
DO $$
BEGIN
    RAISE NOTICE 'WhatsNaija AI database schema installed successfully!';
    RAISE NOTICE 'Next step: Run seed.sql to create test data';
END $$;
